name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge main to gh-pages
      run: |
        git checkout gh-pages
        git merge main --no-edit
        git push origin gh-pages