name: Cron Job Scheduler

on:
  schedule:
    - cron: '0 * * * *' # Runs every day at midnight

jobs:
  update_project:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install from private repository
      run: |
        pip install git+https://$GITHUB_TOKEN:x-oauth-basic@github.com/insightic/pyinsightic.git#egg=pyinsightic
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run pyinsightic and generate files
      run: |
        pyinsightic --name usdc --address xxx social_media > usdc/social_media.json

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add usdc/social_media.json
        git commit -m "cron_update" || echo "No changes to commit"
        git push
