name: Workflow test

on:
    push:
      branches:
        - 'main'
        - 'dev'

jobs:
  run_analysis:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Fetches all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install from private repository
      run: |
        pip install git+https://$GITHUB_TOKEN:x-oauth-basic@github.com/insightic/pyinsightic.git#egg=pyinsightic
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_SECRET }}

    - name: Check pyinsightic availability
      run: python -c "import pyinsightic; print('pyinsightic is available')"
      
    - name: Run pyinsightic SosoValue analysis for the first project directory
      run: |
        for dir in */ ; do
        if [ -f "${dir}data.yml" ]; then
            echo "Processing folder: $dir"
            export PYTHONPATH="$PYTHONPATH:$(pwd)"
            pip list
            which pyinsightic
            pyinsightic pyinsightic.SosoValue(project_dir='$dir').run_analysis()
            echo "Analysis completed for $dir"
            cat "${dir}sosovalue.json"
            break
        fi
        done
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}


